### ISSUE TITLE
paddle_inference开启多线程，推理速度反而更慢，推理速度与多线程数量呈反比

### ISSUE THREAD

**Issue by wsy1991** [PaddlePaddle/Paddle-Inference-Demo#112]

**Comment by wsy1991** [comment]
config.SwitchUseFeedFetchOps(false);
config.SwitchSpecifyInputNames(true);
 config.EnableMemoryOptim();
config.EnableMKLDNN();
config.SetCpuMathLibraryNumThreads(2);
 config.EnableMemoryOptim();
其中NumThreads开启越多，推理速度反而越慢

**Comment by Shixiaowei02** [comment]
https://forum.openmp.org/viewtopic.php?f=3&t=1415
