### ISSUE TITLE
InvalidArgumentError: The input's dimension of Operator(Conv2DFusion) is expected to be 4. But received: input's dimension = 2, shape = [1, 2].

### ISSUE THREAD

**Issue by HWH-2019** [PaddlePaddle/Paddle-Inference-Demo#119]
When I run this：

> python infer_yolov3.py --model_file=./yolov3_infer/__model__ --params_file=./yolov3_infer/__params__ --use_gpu=1

the cmd show：
>W0413 15:44:13.015229 17512 analysis_predictor.cc:677] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I0413 15:44:13.015229 17512 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0413 15:44:13.586211 17512 graph_pattern_detector.cc:101] ---  detected 72 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
I0413 15:44:13.997112 17512 graph_pattern_detector.cc:101] ---  detected 75 subgraphs
e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
I0413 15:44:14.019053 17512 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0413 15:44:14.172643 17512 memory_optimize_pass.cc:200] Cluster name : elementwise_add_20.tmp_0  size: 4096
I0413 15:44:14.172643 17512 memory_optimize_pass.cc:200] Cluster name : elementwise_add_14.tmp_0  size: 2048
I0413 15:44:14.172643 17512 memory_optimize_pass.cc:200] Cluster name : elementwise_add_21.tmp_0  size: 4096
I0413 15:44:14.172643 17512 memory_optimize_pass.cc:200] Cluster name : leaky_relu_51.tmp_0  size: 4096
I0413 15:44:14.173640 17512 memory_optimize_pass.cc:200] Cluster name : leaky_relu_45.tmp_0  size: 4096
I0413 15:44:14.173640 17512 memory_optimize_pass.cc:200] Cluster name : image  size: 12
I0413 15:44:14.173640 17512 memory_optimize_pass.cc:200] Cluster name : elementwise_add_10.tmp_0  size: 1024
I0413 15:44:14.173640 17512 memory_optimize_pass.cc:200] Cluster name : transpose_0.tmp_0  size: 12
I0413 15:44:14.174638 17512 memory_optimize_pass.cc:200] Cluster name : transpose_1.tmp_0  size: 12
I0413 15:44:14.174638 17512 memory_optimize_pass.cc:200] Cluster name : im_size  size: 8
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0413 15:44:14.209545 17512 analysis_predictor.cc:598] ======= optimize end =======
I0413 15:44:14.209545 17512 naive_executor.cc:107] ---  skip [feed], feed -> im_size
I0413 15:44:14.210542 17512 naive_executor.cc:107] ---  skip [feed], feed -> image
I0413 15:44:14.212536 17512 naive_executor.cc:107] ---  skip [elementwise_add_20.tmp_0], fetch -> fetch
W0413 15:44:14.265396 17512 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W0413 15:44:14.279357 17512 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "infer_yolov3.py", line 91, in <module>
    result = run(pred, [im_shape, data, scale_factor])
  File "infer_yolov3.py", line 40, in run
    predictor.run()
ValueError: In user code:

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
    "data_format": data_format,

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/darknet.py", line 68, in _conv_norm
    bias_attr=False)

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/darknet.py", line 154, in __call__
    name=self.prefix_name + "yolo_input")

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/detection/yolo_v3.py", line 507, in build_net
    feats = self.backbone(image)

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/ppyolo.py", line 175, in build_net
    model_out = model.build_net(inputs)

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/load_model.py", line 82, in load_model
    mode='test')

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/command.py", line 158, in main
    model = pdx.load_model(args.model_dir, fixed_input_shape)

    File "/opt/conda/envs/python35-paddle120-env/bin/paddlex", line 10, in <module>
    sys.exit(main())

    InvalidArgumentError: The input's dimension of Operator(Conv2DFusion) is expected to be 4. But received: input's dimension = 2, shape = [1, 2].
      [Hint: Expected in_dims.size() == 4U, but received in_dims.size():2 != 4U:4.] (at D:\v2.0.1\paddle\paddle\fluid\operators\fused\conv_fusion_op.cc:77)
      [operator < conv2d_fusion > error]

I don't know why and how can I solve this problem?

**Comment by jiamingming-004** [comment]
你解决了嘛，我也遇到了同样的问题，希望工作人员可以帮忙解答一下

**Comment by jiamingming-004** [comment]
我看到的解决是，预测的输入有图像、大小、维度 4个输入，你检擦一下你的输入

**Comment by jiamingming-004** [comment]
> When I run this：
> 
> > python infer_yolov3.py --model_file=./yolov3_infer/**model** --params_file=./yolov3_infer/**params** --use_gpu=1
> 
> the cmd show：
> 
> > W0413 15:44:13.015229 17512 analysis_predictor.cc:677] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
> > I0413 15:44:13.015229 17512 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.
> > e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
> > e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
> > e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
> > e[32m--- Running IR pass [is_test_pass]e[0m
> > e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
> > e[32m--- Running IR pass [conv_affine_channel_fuse_pass]e[0m
> > e[32m--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]e[0m
> > e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
> > I0413 15:44:13.586211 17512 graph_pattern_detector.cc:101] ---  detected 72 subgraphs
> > e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
> > e[32m--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]e[0m
> > e[32m--- Running IR pass [multihead_matmul_fuse_pass_v2]e[0m
> > e[32m--- Running IR pass [squeeze2_matmul_fuse_pass]e[0m
> > e[32m--- Running IR pass [reshape2_matmul_fuse_pass]e[0m
> > e[32m--- Running IR pass [flatten2_matmul_fuse_pass]e[0m
> > e[32m--- Running IR pass [map_matmul_to_mul_pass]e[0m
> > e[32m--- Running IR pass [fc_fuse_pass]e[0m
> > e[32m--- Running IR pass [fc_elementwise_layernorm_fuse_pass]e[0m
> > e[32m--- Running IR pass [conv_elementwise_add_act_fuse_pass]e[0m
> > e[32m--- Running IR pass [conv_elementwise_add2_act_fuse_pass]e[0m
> > e[32m--- Running IR pass [conv_elementwise_add_fuse_pass]e[0m
> > I0413 15:44:13.997112 17512 graph_pattern_detector.cc:101] ---  detected 75 subgraphs
> > e[32m--- Running IR pass [transpose_flatten_concat_fuse_pass]e[0m
> > e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
> > e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
> > I0413 15:44:14.019053 17512 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
> > e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
> > e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
> > e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
> > I0413 15:44:14.172643 17512 memory_optimize_pass.cc:200] Cluster name : elementwise_add_20.tmp_0  size: 4096
> > I0413 15:44:14.172643 17512 memory_optimize_pass.cc:200] Cluster name : elementwise_add_14.tmp_0  size: 2048
> > I0413 15:44:14.172643 17512 memory_optimize_pass.cc:200] Cluster name : elementwise_add_21.tmp_0  size: 4096
> > I0413 15:44:14.172643 17512 memory_optimize_pass.cc:200] Cluster name : leaky_relu_51.tmp_0  size: 4096
> > I0413 15:44:14.173640 17512 memory_optimize_pass.cc:200] Cluster name : leaky_relu_45.tmp_0  size: 4096
> > I0413 15:44:14.173640 17512 memory_optimize_pass.cc:200] Cluster name : image  size: 12
> > I0413 15:44:14.173640 17512 memory_optimize_pass.cc:200] Cluster name : elementwise_add_10.tmp_0  size: 1024
> > I0413 15:44:14.173640 17512 memory_optimize_pass.cc:200] Cluster name : transpose_0.tmp_0  size: 12
> > I0413 15:44:14.174638 17512 memory_optimize_pass.cc:200] Cluster name : transpose_1.tmp_0  size: 12
> > I0413 15:44:14.174638 17512 memory_optimize_pass.cc:200] Cluster name : im_size  size: 8
> > e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
> > I0413 15:44:14.209545 17512 analysis_predictor.cc:598] ======= optimize end =======
> > I0413 15:44:14.209545 17512 naive_executor.cc:107] ---  skip [feed], feed -> im_size
> > I0413 15:44:14.210542 17512 naive_executor.cc:107] ---  skip [feed], feed -> image
> > I0413 15:44:14.212536 17512 naive_executor.cc:107] ---  skip [elementwise_add_20.tmp_0], fetch -> fetch
> > W0413 15:44:14.265396 17512 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
> > W0413 15:44:14.279357 17512 device_context.cc:372] device: 0, cuDNN Version: 7.6.
> > Traceback (most recent call last):
> > File "infer_yolov3.py", line 91, in 
> > result = run(pred, [im_shape, data, scale_factor])
> > File "infer_yolov3.py", line 40, in run
> > predictor.run()
> > ValueError: In user code:
> 
> ```
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
> attrs=kwargs.get("attrs", None))
> 
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> return self.main_program.current_block().append_op(*args, **kwargs)
> 
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
> "data_format": data_format,
> 
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/darknet.py", line 68, in _conv_norm
> bias_attr=False)
> 
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/darknet.py", line 154, in __call__
> name=self.prefix_name + "yolo_input")
> 
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/detection/yolo_v3.py", line 507, in build_net
> feats = self.backbone(image)
> 
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/ppyolo.py", line 175, in build_net
> model_out = model.build_net(inputs)
> 
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/load_model.py", line 82, in load_model
> mode='test')
> 
> File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/command.py", line 158, in main
> model = pdx.load_model(args.model_dir, fixed_input_shape)
> 
> File "/opt/conda/envs/python35-paddle120-env/bin/paddlex", line 10, in <module>
> sys.exit(main())
> 
> 
> InvalidArgumentError: The input's dimension of Operator(Conv2DFusion) is expected to be 4. But received: input's dimension = 2, shape = [1, 2].
>   [Hint: Expected in_dims.size() == 4U, but received in_dims.size():2 != 4U:4.] (at D:\v2.0.1\paddle\paddle\fluid\operators\fused\conv_fusion_op.cc:77)
>   [operator < conv2d_fusion > error]
> ```
> 
> I don't know why and how can I solve this problem?

你好，请问你怎么解决的这个问题
