### ISSUE TITLE
win10使用RT报错

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/Paddle-Inference-Demo#17]
![image](https://user-images.githubusercontent.com/7700464/82880354-e415aa00-9f70-11ea-963c-d678fcf25d91.png)
环境： paddlepaddle-gpu-1.8.1.post107
cuda:9.0
系统：win10
python:3.7
执行这句的时候报错
 config.enable_tensorrt_engine(workspace_size = 1<<30,
            max_batch_size=1, min_subgraph_size=5,
            precision_mode=AnalysisConfig.Precision.Float32,
            use_static=False, use_calib_mode=False)

错误信息：
Error: Pass tensorrt_subgraph_pass has not been registered at (D:\1.8.1\paddle\paddle/fluid/framework/ir/pass.h:201)
关掉RT不报错

**Comment by jiweibo** [comment]
pip安装的paddle还不带trt的功能

可以使用这个docker， 有预装带trt功能的python 环境。

docker pull hub.baidubce.com/paddlepaddle/paddle:1.8.0-gpu-cuda10.0-cudnn7-trt6
