### ISSUE TITLE
C++预测demo执行报错："./build/yolov3_test: error while loading shared libraries: libdnnl.so.2"

### ISSUE THREAD

**Issue by Irvingao** [PaddlePaddle/Paddle-Inference-Demo#175]
环境：Ubuntu18.04
CUDA：10.2
cudnn：8.1
TensorRT：7.2.3
Paddle inference：2.1.1预测库（编译好的）

---
编译成功但是执行时报错：不存在libdnnl链接库，但是该链接库就在mkldnn目录下。

![image](https://user-images.githubusercontent.com/58903762/136894461-966f4cc4-fc1d-495f-aecb-ba2f6cb90296.png)

`libdnnl`路径：

![image](https://user-images.githubusercontent.com/58903762/136913451-1c279a82-eee0-4705-993f-dda0587e84d3.png)

**Comment by StephensonDing** [comment]
我也遇到了同样的问题！

**Comment by cerasumat** [comment]
这个问题解决了？
