### ISSUE TITLE
win10  paddle2.0 生成vs解决方案报错：

### ISSUE THREAD

**Issue by qing130** [PaddlePaddle/Paddle-Inference-Demo#188]
按照官网的方法，cmake 的源目录为：Paddle-Inference-Demo-master/c++/x86_linux_demo

然后点击Configure
报错：
CMake Error: The source directory "D:/qing/paddleWork/inference/Paddle-Inference-Demo-master/c++/x86_linux_demo" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by qing130** [comment]
参照的官方教程：https://paddle-inference.readthedocs.io/en/latest/demo_tutorial/x86_windows_demo.html

**Comment by qing130** [comment]
还有，请问一下，直接上传个：在大多数电脑可以运行的vs2019的预测代码例子，这个可行吗

**Comment by qing130** [comment]
cMakeList居然放置在 Paddle-Inference-Demo-master\c++\lib

**Comment by AlisaChen98** [comment]
同在尝试windows编译预测库，想问下您成功了吗

**Comment by qing130** [comment]
> 同在尝试windows编译预测库，想问下您成功了吗

没有

**Comment by qing130** [comment]
没人在win10下用过这个库吗？
