### ISSUE TITLE
教程中的两个windows部署示例有何区别？

### ISSUE THREAD

**Issue by qing130** [PaddlePaddle/Paddle-Inference-Demo#189]
第一个部署示例：https://paddle-inference.readthedocs.io/en/latest/demo_tutorial/x86_windows_demo.html
第二个部署示例：https://paddle-inference.readthedocs.io/en/latest/demo_tutorial/cuda_windows_demo.html#c

是否是第一个例子只跑CPU？

**Comment by BeCoolMaker** [comment]
是的，这是第二个的示例
![image](https://user-images.githubusercontent.com/27920539/160228996-08ce3884-c936-48f6-81fd-7f5427681d2e.png)
