### ISSUE TITLE
请问能给出作为输入数据的具体图像样张的处理示例代码吗？

### ISSUE THREAD

**Issue by YasinFu** [PaddlePaddle/Paddle-Inference-Demo#20]
我使用的是PaddleClass训练生成的模型，是否也可以使用这样的C++接口进行部署，如何处理图像数据为输入的vector<float>,是否需要考虑通道顺序等

**Comment by NHZlX** [comment]
可以的，c++部署可以接受任意paddle训练的模型。后续会在样例中添加真实图像的测试样例

**Comment by anazh** [comment]
图片demo上线了吗
