### ISSUE TITLE
paddle_inference部署demo没有完整的流程体现

### ISSUE THREAD

**Issue by ChaoII** [PaddlePaddle/Paddle-Inference-Demo#213]
1、paddle_inference c++ 部署均是直接赋值模拟数据，对于opencv加载图片，前后处理，赋值等等操作不明确，对于新手直接劝退。
2、paddle_inference c++，python 部署demo可以考虑将典型的模型的全流程放一起，比如识别restnet，检测yolo系列 ，RCNN系列，picodet，分割BiseNet，Unet，自然语言LSTM等等系列模型的全流程，新用户看几个，从模型结构分析，模型输出解码等例子就可以明白整体流程如何。
3、模型部署是一大头，模型部署也是paddlepaddle的核心和优势，这一点如果劝退一波人可能不太好。其实对于其它套件paddledet，paddlesg等可以在里面找到部署的代码，但是里面的全流程封装比较高，文件零散，对于新人思路比较杂乱，对于进阶可以，但是对于入门就不太友好。

**Comment by h1034021643** [comment]
不知道怎么加载图片进去预测

**Comment by h1034021643** [comment]
paddle的文档看着就是好像有 但是没什么卵用

**Comment by gg22mm** [comment]
对现在只有目标检测，其它的都部署代码都在相应该的库中可以找到，就是要去一个一个整出来，有些封装比较高，文件零散 ， 这一块可以考虑出个最简洁不封装的  就好了，这样方便部署

**Comment by qinxue123321** [comment]
其实我都想 转onnx 部署了，没有和opencv结合起来简直醉了，用个随机数据跑的
