### ISSUE TITLE
在jetson nano上用paddle1.6.3跑demo的问题

### ISSUE THREAD

**Issue by jedibobo** [PaddlePaddle/Paddle-Inference-Demo#22]
在跑yolov3使用python接口的demo时遇到的问题
由于paddle版本低于你们要求的，而且有API不支持，我自己修改了infer_yolov3.py部分代码。全在main（）里面
代码修改入下：
if __name__ == '__main__':
    args = parse_args()
    predictor = create_predictor(args)
    img_name = 'kite.jpg'
    save_img_name = 'res.jpg'
    im_size = 608

    img = cv2.imread(img_name)
    data = preprocess(img, im_size)
    im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.int32)

    img_data = PaddleTensor(data)#1.6.3 supported
    img_shape = PaddleTensor(im_shape)
    result = predictor.run([img_data, img_shape])#1.6.3 supported
    result = result[0]
    result_data = result.as_ndarray()  #return numpy.ndarray
    print(result_data.shape)
    result_data = result_data.tolist()
    print(result_data)
    img = Image.open(img_name).convert('RGB').resize((im_size, im_size))
    draw_bbox(img, result=result_data, save_name=save_img_name)

在jetson nano结果如下：paddlepaddle-gpu==1.6.3
Please NOTE: device: 0, CUDA Capability: 53, Driver API Version: 10.0, Runtime API Version: 10.0
I0707 19:41:27.813036 15092 op_compatible_info.cc:201] The default operator required version is missing. Please update the model version.
I0707 19:41:27.813113 15092 analysis_predictor.cc:841] MODEL VERSION: 0.0.0
I0707 19:41:27.813138 15092 analysis_predictor.cc:843] PREDICTOR VERSION: 0.0.0
W0707 19:41:27.813304 15092 analysis_predictor.cc:855]  - Version incompatible (1) batch_norm
W0707 19:41:27.813334 15092 analysis_predictor.cc:855]  - Version incompatible (1) concat
W0707 19:41:27.813356 15092 analysis_predictor.cc:855]  - Version incompatible (1) conv2d
W0707 19:41:27.813376 15092 analysis_predictor.cc:855]  - Version incompatible (1) elementwise_add
W0707 19:41:27.813397 15092 analysis_predictor.cc:855]  - Version incompatible (1) feed
W0707 19:41:27.813417 15092 analysis_predictor.cc:855]  - Version incompatible (1) fetch
W0707 19:41:27.813437 15092 analysis_predictor.cc:855]  - Version incompatible (1) leaky_relu
W0707 19:41:27.813457 15092 analysis_predictor.cc:855]  - Version incompatible (1) multiclass_nms
W0707 19:41:27.813477 15092 analysis_predictor.cc:855]  - Version incompatible (1) nearest_interp
W0707 19:41:27.813495 15092 analysis_predictor.cc:855]  - Version incompatible (1) scale
W0707 19:41:27.813514 15092 analysis_predictor.cc:855]  - Version incompatible (1) transpose2
W0707 19:41:27.813534 15092 analysis_predictor.cc:855]  - Version incompatible (1) yolo_box
W0707 19:41:27.813552 15092 analysis_predictor.cc:144] WARNING: Results may be incorrect! Using same versions between model and lib.

在使用paddlepaddle1.8.0的虚拟机上运行相同的代码（修改后的），图片预测结果也是错误的，但没有报model和lib版本不一的错误。最后预测结果也不正确，请问这个是因为什么原因啊？
个人感觉是不支持算子的原因？有什么在nano上比较好的解决方法吗？

谢谢大佬

**Comment by NHZlX** [comment]
try

```
img_data = PaddleTensor(data)#1.6.3 supported
img_shape = PaddleTensor(im_shape)
```
->

```
img_data = PaddleTensor(data.copy())#1.6.3 supported
img_shape = PaddleTensor(im_shape.copy())
```

**Comment by jedibobo** [comment]
感谢大佬回复，这种方式我在jetson nano上尝试了下，结果依然是错误的。
![image](https://user-images.githubusercontent.com/44748473/87222764-456ecc80-c3a9-11ea-838d-7df62a92db89.png)
不过我在虚拟机打印的信息里看到点信息，我尝试着用官方给的0.0.0版本试一下。目前测试的是1.6.3
![image](https://user-images.githubusercontent.com/44748473/87222782-718a4d80-c3a9-11ea-8ae6-71d14d999f3a.png)

**Comment by jedibobo** [comment]
虚拟机1.8版本可以得到正确结果，我还是怀疑paddle版本的问题
I0711 04:07:22.105757  3481 analysis_predictor.cc:872] MODEL VERSION: 0.0.0
I0711 04:07:22.105763  3481 analysis_predictor.cc:874] PREDICTOR VERSION: 1.8.0
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [fc_lstm_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0711 04:07:23.583334  3481 graph_pattern_detector.cc:101] ---  detected 72 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0711 04:07:23.657356  3481 memory_optimize_pass.cc:223] Cluster name : im_size  size: 8
I0711 04:07:23.657424  3481 memory_optimize_pass.cc:223] Cluster name : leaky_relu_0.tmp_0  size: 47316992
I0711 04:07:23.657430  3481 memory_optimize_pass.cc:223] Cluster name : batch_norm_0.tmp_2  size: 47316992
I0711 04:07:23.657433  3481 memory_optimize_pass.cc:223] Cluster name : elementwise_add_12  size: 2957312
I0711 04:07:23.657435  3481 memory_optimize_pass.cc:223] Cluster name : image  size: 4435968
I0711 04:07:23.657438  3481 memory_optimize_pass.cc:223] Cluster name : elementwise_add_20  size: 1478656
I0711 04:07:23.657441  3481 memory_optimize_pass.cc:223] Cluster name : batch_norm_1.tmp_2  size: 23658496
I0711 04:07:23.657444  3481 memory_optimize_pass.cc:223] Cluster name : yolo_box2.tmp_0  size: 277248
I0711 04:07:23.657446  3481 memory_optimize_pass.cc:223] Cluster name : leaky_relu_3.tmp_0  size: 23658496
I0711 04:07:23.657449  3481 memory_optimize_pass.cc:223] Cluster name : yolo_box1.tmp_0  size: 69312
I0711 04:07:23.657452  3481 memory_optimize_pass.cc:223] Cluster name : yolo_box0.tmp_0  size: 17328
--- Running analysis [ir_graph_to_program_pass]
I0711 04:07:23.687988  3481 analysis_predictor.cc:493] ======= optimize end =======
I0711 04:07:23.688092  3481 naive_executor.cc:95] ---  skip [feed], feed -> im_size
I0711 04:07:23.688099  3481 naive_executor.cc:95] ---  skip [feed], feed -> image
I0711 04:07:23.689632  3481 naive_executor.cc:95] ---  skip [leaky_relu_0.tmp_0], fetch -> fetch
category id is 0.0, bbox is [ 98.47467 471.34286 120.73273 578.5183 ]
category id is 0.0, bbox is [ 51.75272 415.51324  73.18762 515.24005]
category id is 0.0, bbox is [ 37.176304 343.378     46.64221  380.92963 ]
category id is 0.0, bbox is [155.78638 328.0806  159.5393  339.37192]
category id is 0.0, bbox is [233.86328 339.96912 239.35403 355.3322 ]
category id is 0.0, bbox is [ 16.212902 344.42365   25.193726 377.97137 ]
category id is 0.0, bbox is [ 10.583471 356.67862   14.9261   372.8137  ]
category id is 0.0, bbox is [ 79.76479 364.19492  86.07656 385.64255]
category id is 0.0, bbox is [312.8938  311.9908  314.58527 316.60056]
category id is 33.0, bbox is [266.97925   51.700447 299.45105   99.99642 ]
category id is 33.0, bbox is [210.45593 229.92128 217.77551 240.97136]
category id is 33.0, bbox is [125.36278 159.80173 135.49306 189.89758]
category id is 33.0, bbox is [486.9354  266.164   494.4437  283.84637]
category id is 33.0, bbox is [259.01584 232.23044 270.69266 248.58704]
category id is 33.0, bbox is [135.60567 254.57668 144.96178 276.9275 ]
category id is 33.0, bbox is [341.91315 255.44394 345.0335  262.3398 ]

**Comment by NHZlX** [comment]
1.6.3版本确实比较旧了，中间有修复挺多bug。可以更新下版本，如果新版本有问题可以发到这里，我会继续跟进。

**Comment by jedibobo** [comment]
抱歉。。我差点忘了这茬。
在多次失败后我就重新编译了Paddle
目前用的2.0.0版本没有问题

贴一下解决完写的博客
https://blog.csdn.net/qq_44498043/article/details/107300374

感谢您的回复
