### ISSUE TITLE
cmake生成vs2022工程，编译报错，无法解析的外部符号 OrtGetApiBase

### ISSUE THREAD

**Issue by dogpandacat** [PaddlePaddle/Paddle-Inference-Demo#280]
1、环境：Win10 64位
2、使用Paddle Inference 的c++ sdk进行推理部署
3、用cmake生成vs2022工程，打开工程进行编译，直接报错，链接失败，详细检查过vs的各种配置，发现没有啥问题

有大神知道是怎么回事吗？谢谢了

![UUI_{VQEH_$UEQ(4XC5F458](https://user-images.githubusercontent.com/4141550/170921736-95d1e086-e36b-413f-8cc0-1628e3bd729b.png)

**Comment by heliqi** [comment]
使用这个[demo](https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/paddle-onnxruntime)中的cmakelist, 并在cmake编译时设置WITH_ONNXRUNTIME属性为ON

**Comment by ANDROIDTODO** [comment]
BUILD_TYPE 设置为Release
<img width="366" alt="企业微信截图_16559014652496" src="https://user-images.githubusercontent.com/10429542/175031005-053beef5-90e8-40df-8bdb-54ac03cd6e23.png">
