### ISSUE TITLE
yolov7推断速度相对torch增加了30倍 开启tensorrt时报错

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/Paddle-Inference-Demo#343]
```
import paddle
import cv2
import paddle.inference as paddle_infer
import numpy as np
import time
from ops import multiclass_nms
from paddle.inference import PrecisionType
config = paddle_infer.Config("pd_model2/inference_model/model.pdmodel","pd_model2/inference_model/model.pdiparams")
config.enable_memory_optim()
config.enable_use_gpu(1000, 0)
config.enable_tensorrt_engine(workspace_size=1 << 30,
                                max_batch_size=1,
                                min_subgraph_size=5,
                                precision_mode=PrecisionType.Float32,
                                use_static=False,
                                use_calib_mode=False)
predictor = paddle_infer.create_predictor(config)
```

```
ValueError                                Traceback (most recent call last)
<ipython-input-7-e69dc2abcffd> in <module>
     15                                 use_static=False,
     16                                 use_calib_mode=False)
---> 17 predictor = paddle_infer.create_predictor(config)
     18 
     19 input_names = predictor.get_input_names()

ValueError: (InvalidArgument) Pass preln_embedding_eltwise_layernorm_fuse_pass has not been registered.
  [Hint: Expected Has(pass_type) == true, but received Has(pass_type):0 != true:1.] (at /paddle/paddle/fluid/framework/ir/pass.h:242)
```

**Comment by janelu9** [comment]
还有就是用torch直接预估yolov7 只需要10ms 左右 转成onnx再转成paddle预测需要300ms
gpu是 rtx3060
paddlepaddle-gpu                   2.3.0.post112

**Comment by janelu9** [comment]
另外 X2paddle不支持float16的torch模型转换 float32的虽然可以转成 预测结果误差很大或者说根本不对 通过onnx中转  还能用 就是耗时 有点太大了

**Comment by wjj19950828** [comment]
@janelu9 麻烦提供一下torch2paddle的复现脚本以及onnx模型吧，这边看下

然后请问下具体业务场景是什么呢，为什么会有转到paddle部署的需求呢

**Comment by janelu9** [comment]
> @janelu9 麻烦提供一下torch2paddle的复现脚本以及onnx模型吧，这边看下
> 
> 然后请问下具体业务场景是什么呢，为什么会有转到paddle部署的需求呢

因为是个组合模型后面的模型用的都是paddle 而且推理镜像里只有paddle没装torch

**Comment by janelu9** [comment]
```
with torch.no_grad():
    pred=model(dummy_input)
torch.onnx.export(model, dummy_input, "yolov7x2.onnx", verbose=True, input_names=input_names, output_names=output_names)
!x2paddle --framework=onnx --model=yolov7x2.onnx --save_dir=pd_model2
```

**Comment by wjj19950828** [comment]
> 还有就是用torch直接预估yolov7 只需要10ms 左右 转成onnx再转成paddle预测需要300ms

@janelu9 这个是如何测速的呢，测速脚本也发我一份吧～

**Comment by janelu9** [comment]
> > 还有就是用torch直接预估yolov7 只需要10ms 左右 转成onnx再转成paddle预测需要300ms
> 
> @janelu9 这个是如何测速的呢，测速脚本也发我一份吧～

import paddle
import cv2
import paddle.inference as paddle_infer
import numpy as np
from paddle.inference import PrecisionType

config = paddle_infer.Config("pd_model2/inference_model/model.pdmodel","pd_model2/inference_model/model.pdiparams")

config.enable_use_gpu(1000, 0)

predictor = paddle_infer.create_predictor(config)

input_names = predictor.get_input_names()
output_names = predictor.get_output_names()
output_handle = predictor.get_output_handle(output_names[0])
input_handle = predictor.get_input_handle(input_names[0])
input_handle.reshape([1,3,640,640])

img0 = cv2.imread('inference/images/horses.jpg')  

img,*ratio_pad=preprocess(img0)

input_handle.copy_from_cpu(img)
st = time.time()
predictor.run()
print(time.time()-st)
output_data = output_handle.copy_to_cpu()
print(time.time()-st)

**Comment by janelu9** [comment]
模型你可以去yolov7那个github上面下载yolov7x.pt

**Comment by wjj19950828** [comment]
@janelu9 您好，我这边测了一下，主要有以下几个问题哈：
1、[yolov7](https://github.com/WongKinYiu/yolov7)这个repo，在运行detect.py时需要注意两个点
- 输入大小是1，3，448，640，但转换的ONNX模型输入大小为1，3，640，640，建议输入对齐
- 脚本中默认half是开启，也就是模型参数以及输入的类型都是float16，但是上面测试脚本是float32，这个也会有影响

2、在测速的时候建议先warmup一下，因为随机性非常大，这里我warmup 100次，然后测试1000次去平均，具体结果如下：
| 输入shape | Dynamic(ms) | PaddleInference(ms) |
|-----|----|----|
| 1,3,640,640 | 24.69 | 22.30 |

上面结果都为float32，与yolov7官方demo float16 输入1,3,448,640的 10.9ms差距其实在预期之类，Dynamic代表使用的是paddle.jit.load接口，PaddleInference代表使用的是PaddleInference接口，具体测试代码如下：

**Dynamic:**
```code
import paddle
import sys
import os
import numpy as np
import pickle
import time

inputs = np.load("real_img.npy")

inputs = paddle.to_tensor(inputs)

warmup_count = 100
count = 1000
# trace
model = paddle.jit.load("pd_model/inference_model/", model_filename="model.pdmodel", params_filename="model.pdiparams")
for i in range(warmup_count):
    result = model(inputs)
start = time.time()
for i in range(count):
    result = model(inputs)
elapsed_ms = (time.time() - start) * 1000
print("Latency: {:.2f} ms".format(elapsed_ms / count))
```

**PaddleInference**
```code
import os
import cv2
import glob
import argparse
import pickle
import numpy as np
import time

from pathlib import Path
import paddle
import paddle.fluid as fluid
from paddle.inference import create_predictor, PrecisionType
from paddle.inference import Config

def parse_args():
    parser = argparse.ArgumentParser(description='Model inference')
    parser.add_argument(
        '--batch_size',
        dest='batch_size',
        help='Mini batch size of one gpu or cpu.',
        type=int,
        default=1)
    parser.add_argument(
        "--precision",
        default="fp32",
        type=str,
        choices=["fp32", "fp16", "int8"],
        help='The tensorrt precision.')
    parser.add_argument(
        '--enable_auto_tune',
        default=False,
        type=eval,
        choices=[True, False],
        help='Whether to enable tuned dynamic shape. We uses some images to collect '
        'the dynamic shape for trt sub graph, which avoids setting dynamic shape manually.'
    )
    def str2bool(v):
        return v.lower() in ("true", "t", "1")
    parser.add_argument("--use_gpu", type=str2bool, default=True)
    parser.add_argument("--enable_trt", type=str2bool, default=False, help="enable trt")
    parser.add_argument("--cpu_threads", type=int, default=1)
    parser.add_argument("--enable_mkldnn", type=str2bool, default=False)
    return parser.parse_args()

def load_predictor(model_dir,
                   batch_size=1,
                   use_gpu=False,
                   enable_trt=False,
                   cpu_threads=1,
                   enable_mkldnn=False,
                   enable_dynamic_shape=False):
    """set AnalysisConfig, generate AnalysisPredictor
    Args:
        model_dir (str): root path of __model__ and __params__
        use_gpu (bool): whether use gpu
    Returns:
        predictor (PaddlePredictor): AnalysisPredictor
    """
    config = Config(
        os.path.join(model_dir, 'model.pdmodel'),
        os.path.join(model_dir, 'model.pdiparams'))
    if use_gpu:
        # initial GPU memory(M), device ID
        config.enable_use_gpu(200, 0)
        # optimize graph and fuse op
        config.switch_ir_optim(True)
        if enable_trt:
            try:
                config.enable_tensorrt_engine(
                    workspace_size=1 << 30,
                    precision_mode=PrecisionType.Float32,
                    max_batch_size=1,
                    min_subgraph_size=3)
                if enable_dynamic_shape:
                    # config.collect_shape_range_info("shape.pbtxt")
                    config.enable_tuned_tensorrt_dynamic_shape("shape.pbtxt", True)
            except Exception as e:
                print(
                    "The current environment does not support `tensorrt`, so disable tensorrt."
                )
                pass
    else:
        config.disable_gpu()
        config.set_cpu_math_library_num_threads(cpu_threads)
        if enable_mkldnn:
            try:
                # cache 10 different shapes for mkldnn to avoid memory leak
                config.set_mkldnn_cache_capacity(10)
                config.enable_mkldnn()
            except Exception as e:
                print(
                    "The current environment does not support `mkldnn`, so disable mkldnn."
                )
                pass

    config.enable_memory_optim()
    # disable feed, fetch OP, needed by zero_copy_run
    config.switch_use_feed_fetch_ops(False)
    pass_builder = config.pass_builder()
    predictor = create_predictor(config)
    return predictor, config

class InferPipeline:
    def __init__(self, model_dir, model_name, batch_size=1, use_gpu=True, enable_trt=True, cpu_threads=1, enable_mkldnn=True, enable_dynamic_shape=False):
        self.predictor, self.config = load_predictor(
            model_dir,
            batch_size=batch_size,
            use_gpu=use_gpu,
            enable_trt=enable_trt,
            cpu_threads=cpu_threads,
            enable_mkldnn=enable_mkldnn,
            enable_dynamic_shape=enable_dynamic_shape)
        self.model_name = model_name
        self.batch_size = batch_size

    def run(self, data=None, warmup=0, repeats=1, abs_diff_threshold=1e-05, relative_diff_threshold=1e-05):
        if repeats == 0:
            assert 'repeat nums should greater than 0'
        results = None

        input_names = self.predictor.get_input_names()
        output_names = self.predictor.get_output_names()
        for i in range(warmup):
            for i in range(len(input_names)):
                input_tensor = self.predictor.get_input_handle(input_names[i])
                input_tensor.copy_from_cpu(data)
            self.predictor.run()
            results = []
            for output_name in output_names:
                output_tensor = self.predictor.get_output_handle(output_name)
                results.append(output_tensor.copy_to_cpu())
        for i in range(len(input_names)):
            input_tensor = self.predictor.get_input_handle(input_names[i])
            input_tensor.copy_from_cpu(data)
        start_time = time.time()
        for i in range(repeats):
            self.predictor.run()
        elapsed_ms = (time.time() - start_time) * 1000
        print("Latency: {:.2f} ms".format(elapsed_ms / repeats))
        results = []
        for output_name in output_names:
            output_tensor = self.predictor.get_output_handle(output_name)
            results.append(output_tensor.copy_to_cpu())

        return results

def main(args):
    inputs = np.load("real_img.npy")
    infer_pipeline = InferPipeline(model_dir="pd_model/inference_model/",
                                           model_name='Yolov7',
                                           use_gpu=args.use_gpu,
                                           enable_trt=args.enable_trt,
                                           cpu_threads=args.cpu_threads,
                                           enable_mkldnn=args.enable_mkldnn,
                                           enable_dynamic_shape=args.enable_auto_tune)
    # inference
    results = infer_pipeline.run(data=inputs, warmup=100, repeats=1000)
    print(results[0].shape)
    
if __name__ == '__main__':
    args = parse_args()
    main(args)
```

另外如果遇到TRT的问题，建议去Paddle官网Issue去提Bug，会有专门的人看相关问题

感谢反馈～

**Comment by janelu9** [comment]
> @janelu9 您好，我这边测了一下，主要有以下几个问题哈： 1、[yolov7](https://github.com/WongKinYiu/yolov7)这个repo，在运行detect.py时需要注意两个点
> 
> * 输入大小是1，3，448，640，但转换的ONNX模型输入大小为1，3，640，640，建议输入对齐
> * 脚本中默认half是开启，也就是模型参数以及输入的类型都是float16，但是上面测试脚本是float32，这个也会有影响
> 
> 2、在测速的时候建议先warmup一下，因为随机性非常大，这里我warmup 100次，然后测试1000次去平均，具体结果如下：
> 
> 输入shape	Dynamic(ms)	PaddleInference(ms)
> 1,3,640,640	24.69	22.30
> 上面结果都为float32，与yolov7官方demo float16 输入1,3,448,640的 10.9ms差距其实在预期之类，Dynamic代表使用的是paddle.jit.load接口，PaddleInference代表使用的是PaddleInference接口，具体测试代码如下：
> 
> **Dynamic:**
> 
> ```
> import paddle
> import sys
> import os
> import numpy as np
> import pickle
> import time
> 
> inputs = np.load("real_img.npy")
> 
> inputs = paddle.to_tensor(inputs)
> 
> warmup_count = 100
> count = 1000
> # trace
> model = paddle.jit.load("pd_model/inference_model/", model_filename="model.pdmodel", params_filename="model.pdiparams")
> for i in range(warmup_count):
>     result = model(inputs)
> start = time.time()
> for i in range(count):
>     result = model(inputs)
> elapsed_ms = (time.time() - start) * 1000
> print("Latency: {:.2f} ms".format(elapsed_ms / count))
> ```
> 
> **PaddleInference**
> 
> ```
> import os
> import cv2
> import glob
> import argparse
> import pickle
> import numpy as np
> import time
> 
> from pathlib import Path
> import paddle
> import paddle.fluid as fluid
> from paddle.inference import create_predictor, PrecisionType
> from paddle.inference import Config
> 
> def parse_args():
>     parser = argparse.ArgumentParser(description='Model inference')
>     parser.add_argument(
>         '--batch_size',
>         dest='batch_size',
>         help='Mini batch size of one gpu or cpu.',
>         type=int,
>         default=1)
>     parser.add_argument(
>         "--precision",
>         default="fp32",
>         type=str,
>         choices=["fp32", "fp16", "int8"],
>         help='The tensorrt precision.')
>     parser.add_argument(
>         '--enable_auto_tune',
>         default=False,
>         type=eval,
>         choices=[True, False],
>         help='Whether to enable tuned dynamic shape. We uses some images to collect '
>         'the dynamic shape for trt sub graph, which avoids setting dynamic shape manually.'
>     )
>     def str2bool(v):
>         return v.lower() in ("true", "t", "1")
>     parser.add_argument("--use_gpu", type=str2bool, default=True)
>     parser.add_argument("--enable_trt", type=str2bool, default=False, help="enable trt")
>     parser.add_argument("--cpu_threads", type=int, default=1)
>     parser.add_argument("--enable_mkldnn", type=str2bool, default=False)
>     return parser.parse_args()
> 
> def load_predictor(model_dir,
>                    batch_size=1,
>                    use_gpu=False,
>                    enable_trt=False,
>                    cpu_threads=1,
>                    enable_mkldnn=False,
>                    enable_dynamic_shape=False):
>     """set AnalysisConfig, generate AnalysisPredictor
>     Args:
>         model_dir (str): root path of __model__ and __params__
>         use_gpu (bool): whether use gpu
>     Returns:
>         predictor (PaddlePredictor): AnalysisPredictor
>     """
>     config = Config(
>         os.path.join(model_dir, 'model.pdmodel'),
>         os.path.join(model_dir, 'model.pdiparams'))
>     if use_gpu:
>         # initial GPU memory(M), device ID
>         config.enable_use_gpu(200, 0)
>         # optimize graph and fuse op
>         config.switch_ir_optim(True)
>         if enable_trt:
>             try:
>                 config.enable_tensorrt_engine(
>                     workspace_size=1 << 30,
>                     precision_mode=PrecisionType.Float32,
>                     max_batch_size=1,
>                     min_subgraph_size=3)
>                 if enable_dynamic_shape:
>                     # config.collect_shape_range_info("shape.pbtxt")
>                     config.enable_tuned_tensorrt_dynamic_shape("shape.pbtxt", True)
>             except Exception as e:
>                 print(
>                     "The current environment does not support `tensorrt`, so disable tensorrt."
>                 )
>                 pass
>     else:
>         config.disable_gpu()
>         config.set_cpu_math_library_num_threads(cpu_threads)
>         if enable_mkldnn:
>             try:
>                 # cache 10 different shapes for mkldnn to avoid memory leak
>                 config.set_mkldnn_cache_capacity(10)
>                 config.enable_mkldnn()
>             except Exception as e:
>                 print(
>                     "The current environment does not support `mkldnn`, so disable mkldnn."
>                 )
>                 pass
> 
>     config.enable_memory_optim()
>     # disable feed, fetch OP, needed by zero_copy_run
>     config.switch_use_feed_fetch_ops(False)
>     pass_builder = config.pass_builder()
>     predictor = create_predictor(config)
>     return predictor, config
> 
> class InferPipeline:
>     def __init__(self, model_dir, model_name, batch_size=1, use_gpu=True, enable_trt=True, cpu_threads=1, enable_mkldnn=True, enable_dynamic_shape=False):
>         self.predictor, self.config = load_predictor(
>             model_dir,
>             batch_size=batch_size,
>             use_gpu=use_gpu,
>             enable_trt=enable_trt,
>             cpu_threads=cpu_threads,
>             enable_mkldnn=enable_mkldnn,
>             enable_dynamic_shape=enable_dynamic_shape)
>         self.model_name = model_name
>         self.batch_size = batch_size
> 
>     def run(self, data=None, warmup=0, repeats=1, abs_diff_threshold=1e-05, relative_diff_threshold=1e-05):
>         if repeats == 0:
>             assert 'repeat nums should greater than 0'
>         results = None
> 
>         input_names = self.predictor.get_input_names()
>         output_names = self.predictor.get_output_names()
>         for i in range(warmup):
>             for i in range(len(input_names)):
>                 input_tensor = self.predictor.get_input_handle(input_names[i])
>                 input_tensor.copy_from_cpu(data)
>             self.predictor.run()
>             results = []
>             for output_name in output_names:
>                 output_tensor = self.predictor.get_output_handle(output_name)
>                 results.append(output_tensor.copy_to_cpu())
>         for i in range(len(input_names)):
>             input_tensor = self.predictor.get_input_handle(input_names[i])
>             input_tensor.copy_from_cpu(data)
>         start_time = time.time()
>         for i in range(repeats):
>             self.predictor.run()
>         elapsed_ms = (time.time() - start_time) * 1000
>         print("Latency: {:.2f} ms".format(elapsed_ms / repeats))
>         results = []
>         for output_name in output_names:
>             output_tensor = self.predictor.get_output_handle(output_name)
>             results.append(output_tensor.copy_to_cpu())
> 
>         return results
> 
> def main(args):
>     inputs = np.load("real_img.npy")
>     infer_pipeline = InferPipeline(model_dir="pd_model/inference_model/",
>                                            model_name='Yolov7',
>                                            use_gpu=args.use_gpu,
>                                            enable_trt=args.enable_trt,
>                                            cpu_threads=args.cpu_threads,
>                                            enable_mkldnn=args.enable_mkldnn,
>                                            enable_dynamic_shape=args.enable_auto_tune)
>     # inference
>     results = infer_pipeline.run(data=inputs, warmup=100, repeats=1000)
>     print(results[0].shape)
>     
> if __name__ == '__main__':
>     args = parse_args()
>     main(args)
> ```
> 
> 另外如果遇到TRT的问题，建议去Paddle官网Issue去提Bug，会有专门的人看相关问题
> 
> 感谢反馈～

我测的时候输入的两边数据是一样的都是1,3,640,640，float32 
我的gpu是rtx3060
torch10ms左右 paddleinfer最快也要200ms

**Comment by janelu9** [comment]
![image](https://user-images.githubusercontent.com/24219258/184292301-4d5ccc1b-770b-4f1c-a1fd-45304afd953c.png)
