### ISSUE TITLE
在nano上跑官方demo的infer_yolov3无法使用GPU加速

### ISSUE THREAD

**Issue by Fitz-Fitz** [PaddlePaddle/Paddle-Inference-Demo#41]
use_gpu=1，加载模型全部正常，但是最后报错如下

W1112 08:38:37,097999 16867 devlce context.cc:237] Please NOTE: device:  0,  CUDA capability: 53 ,Driver API Version : 10.2, Runtime API Version: 10.0
W1112 08:38:37.226699 16867 devlce context.cc:245] devlce:  0, cuDNN Version: 8.0.
W1112 08:38:43.420408 16867 init.cc:209] Warntng: PaddlePaddle catches a fatlure signal, it may not work properly
W1112 08:38:43.420493 16867 init.cc:211] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1112 08:38:43.420511 16867 init.cc:214] The detail failure signal is:

W1112 08:38:43.420527 16867 init.cc:217] *** Aborted at 1605188323 (unix time) try "date -d @1605188323" Lf you are using GNU date ***
W1112 08:38:43.426568 16867 init.cc:217] PC:  @                          0x0(unknown)
W1112 08:38:43 448750 16867 init.cc:217] *** SIGSECV (@0x0) received by PID 16867 (TID 0x7fa0dfd010) from PID 0; stack trace: ***
W1112 08:38:43.455078 16867 init.cc:217]        @          0x7fa0e046c0 ([vdso]+0x6bf) 
Segmentation fault (core dumped)

**Comment by cryoco** [comment]
您好，看起来是内存爆了导致进程被kill了。
您可以尝试：
1. 在AnalysisConfig中通过`config->EnableMemoryOpitm();`接口降低内存/显存占用；
2. 清理系统中常驻内存且用不到的进程；
3. 如果仍报错的话，可以参考[此文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_guide/inference_deployment/inference/build_and_install_lib_cn.html#id12)设置或增加swap空间：
![image](https://user-images.githubusercontent.com/12407750/99023410-89fcb580-259f-11eb-9c15-ee51775f84d7.png)
注意使用swap空间会导致推理性能下降，要避免这种情况可以考虑使用更小的模型和输入size，毕竟nano内存与显存共用，且容量不大。

**Comment by Fitz-Fitz** [comment]
感谢，经过排查可能是因为paddle和jetpack版本不符，jetpack4.4的CUDA是10.2，Cudnn是8，而我下载编译的paddle inference 提供的cuda 运行环境是10。
今天重刷系统滚回jetpack4.3后，可以使用GPU跑demo了，但是出现了新的问题
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > paddle::platform::GetTraceBackString<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int)
2   paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
3   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::NaiveExecutor::Run()
8   paddle::AnalysisPredictor::ZeroCopyRun()

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
    "data_format": data_format,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/mobilenet_v3.py", line 201, in _conv_bn_layer
    bias_attr=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/mobilenet_v3.py", line 368, in __call__
    name='conv1')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/nets/detection/yolo_v3.py", line 502, in build_net
    feats = self.backbone(image)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/ppyolo.py", line 171, in build_net
    model_out = model.build_net(inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/cv/models/load_model.py", line 66, in load_model
    mode='test')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlex/command.py", line 156, in main
    model = pdx.load_model(args.model_dir, fixed_input_shape)
  File "/opt/conda/envs/python35-paddle120-env/bin/paddlex", line 10, in <module>
    sys.exit(main())

----------------------
Error Message Summary:
----------------------
Error: input and filter data type should be consistent
  [Hint: Expected input_data_type == filter_data_type, but received input_data_type:2 != filter_data_type:5.] at (/home/paddle/github/paddle/paddle/fluid/operators/conv_op.cc:172)
  [operator < conv2d_fusion > error]


这个问题昨天跑是没有出现的，今天换到jetpack4.3之后再跑同样的代码就报错有输入数据不匹配，请问有什么推荐的解决方案不

**Comment by cryoco** [comment]
这个报错是说您的conv op的输入类型和filter类型不匹配，输入是int32，filter是float，可以检查下模型是否有这个问题

**Comment by Fitz-Fitz** [comment]
感谢您

**Comment by Fitz-Fitz** [comment]
> 这个报错是说您的conv op的输入类型和filter类型不匹配，输入是int32，filter是float，可以检查下模型是否有这个问题

能麻烦您瞅一眼43不，感谢感谢

**Comment by cryoco** [comment]
您说的43是指？

**Comment by Fitz-Fitz** [comment]
https://github.com/PaddlePaddle/Paddle-Inference-Demo/issues/43
麻烦您了

**Comment by cryoco** [comment]
哦哦好的，我们目前还没有监控这个repo哈，有可能会漏掉您的issue，您可以发在[这里](https://github.com/PaddlePaddle/Paddle/issues)哈，每天会有值班同学跟进，谢谢

**Comment by Fitz-Fitz** [comment]
好嘞，感谢您
