### ISSUE TITLE
部署怎样和c++ opencv结合

### ISSUE THREAD

**Issue by qinxue123321** [PaddlePaddle/Paddle-Inference-Demo#412]
不是cmake那种编译，是在visualstudio2019上 opencv3.4.6读取图片后，不到怎么把Mat转成input_tensor，还望大佬给点建议

**Comment by BrilliantYuKaimin** [comment]
可以参考 PaddleSeg 的 C++ 部署示例：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/deploy/cpp/src/test_seg.cc
