### ISSUE TITLE
Paddle-Inference目前有计划double类型吗?

### ISSUE THREAD

**Issue by ccsuzzh** [PaddlePaddle/Paddle-Inference-Demo#427]
Paddle-Inference目前有计划double类型吗?

**Comment by GoXian** [comment]
我使用double报错

**Comment by ccsuzzh** [comment]
> 我使用double报错

这是相关PR：https://github.com/PaddlePaddle/Paddle/pull/51786，确认一下你使用的Paddle版本是否已经支持了。

**Comment by GoXian** [comment]
> > 我使用double报错
> 
> 这是相关PR：[https://github.com/PaddlePaddle/Paddle/pull/51786，确认一下你使用的Paddle版本是否已经支持了。](https://github.com/PaddlePaddle/Paddle/pull/51786%EF%BC%8C%E7%A1%AE%E8%AE%A4%E4%B8%80%E4%B8%8B%E4%BD%A0%E4%BD%BF%E7%94%A8%E7%9A%84Paddle%E7%89%88%E6%9C%AC%E6%98%AF%E5%90%A6%E5%B7%B2%E7%BB%8F%E6%94%AF%E6%8C%81%E4%BA%86%E3%80%82)

这个链接，打开显示 Page not found

**Comment by ccsuzzh** [comment]
现在可以了。

**Comment by ccsuzzh** [comment]
> > > 我使用double报错
> > 
> > 
> > 这是相关PR：[https://github.com/PaddlePaddle/Paddle/pull/51786，确认一下你使用的Paddle版本是否已经支持了。](https://github.com/PaddlePaddle/Paddle/pull/51786%EF%BC%8C%E7%A1%AE%E8%AE%A4%E4%B8%80%E4%B8%8B%E4%BD%A0%E4%BD%BF%E7%94%A8%E7%9A%84Paddle%E7%89%88%E6%9C%AC%E6%98%AF%E5%90%A6%E5%B7%B2%E7%BB%8F%E6%94%AF%E6%8C%81%E4%BA%86%E3%80%82)
> 
> 这个链接，打开显示 Page not found

现在可以了。

**Comment by GoXian** [comment]
> > > > 我使用double报错
> > > 
> > > 
> > > 这是相关PR：[https://github.com/PaddlePaddle/Paddle/pull/51786，确认一下你使用的Paddle版本是否已经支持了。](https://github.com/PaddlePaddle/Paddle/pull/51786%EF%BC%8C%E7%A1%AE%E8%AE%A4%E4%B8%80%E4%B8%8B%E4%BD%A0%E4%BD%BF%E7%94%A8%E7%9A%84Paddle%E7%89%88%E6%9C%AC%E6%98%AF%E5%90%A6%E5%B7%B2%E7%BB%8F%E6%94%AF%E6%8C%81%E4%BA%86%E3%80%82)
> > 
> > 
> > 这个链接，打开显示 Page not found
> 
> 现在可以了。

还是无法打开。

**Comment by ccsuzzh** [comment]
https://github.com/PaddlePaddle/Paddle/pull/51786

**Comment by GoXian** [comment]
> [PaddlePaddle/Paddle#51786](https://github.com/PaddlePaddle/Paddle/pull/51786)

谢了
