### ISSUE TITLE
使用paddle inference创建预测器时显示无法读取模型文件

### ISSUE THREAD

**Issue by amiscolo** [PaddlePaddle/Paddle-Inference-Demo#430]
问题：使用paddle inference创建预测器时显示无法读取模型文件

报警信息： 
![屏幕截图 2023-03-18 122328](https://user-images.githubusercontent.com/125656584/226084780-027308ba-c9dd-4c89-9fb7-c0027ad92b61.png)

代码如下：
![屏幕截图 2023-03-18 122415](https://user-images.githubusercontent.com/125656584/226084798-6f6200c2-ec78-42bc-9952-d0aab95088a3.png)

提问之前我已确认：
①python文件路径的三种写法均已尝试但依然报错
②使用模型张量分析代码确认文件可访问
③模型是在百度飞桨模型库下载的模型，根据paddle inference文档，paddle inference支持百度飞浆上面的所有模型
④使用PaddleDetection脚本确认过模型可以运行，只是在使用paddle inference时无法创建

**Comment by vivienfanghuagood** [comment]
model_file和params_file仅保留文件名去掉文件路径试试呢。
