### ISSUE TITLE
可否不依赖完整的Paddle

### ISSUE THREAD

**Issue by SWHL** [PaddlePaddle/Paddle-Inference-Demo#438]
- 考虑到对整个Paddle库的依赖，感觉PaddleInference使用不太友好。
- [onnxruntime](https://pypi.org/project/onnxruntime/#files)推理引擎最大只有6.6M
- [paddlepaddle](https://pypi.org/project/paddlepaddle/#files)最小却有47M
- 是否可以考虑单独出一个推理版的paddle inference呢？

**Comment by vivienfanghuagood** [comment]
我们会评估这个需求～
