### ISSUE TITLE
关于paddle inference的精度调试工具

### ISSUE THREAD

**Issue by tianyuzhou668** [PaddlePaddle/Paddle-Inference-Demo#480]
您好，我这边看到关于paddle inference的精度调试工具目前的Demo是基于trt的，请问是否支持paddle inference呢？基于Paddle inference的Demo又应该如何修改呢？https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/python/advanced/tensorrt_precision_debug/README.md

**Comment by vivienfanghuagood** [comment]
@ming1753  麻烦关注一下这个问题哈

**Comment by ming1753** [comment]
当前代码也是同时支持paddle inference的，只需要根据实际使用场景，修改init_predictor中predictor的创建方式即可。
