### ISSUE TITLE
编译c++的resnet50推理代码，提示缺少libphi.so文件，请问可以在哪下载？下的linux推理包里面没有带libphi.so

### ISSUE THREAD

**Issue by funny000** [PaddlePaddle/Paddle-Inference-Demo#504]

**Comment by funny000** [comment]
cmakelist.txt 里面写了option(with_shared_phi "content" OFF)，但是还是提示缺少libphi.so

**Comment by carryyu** [comment]
https://www.paddlepaddle.org.cn/inference/v2.6/guides/install/download_lib.html

可以在这个链接下面找到C++推理库，解压后在paddle_inference/paddle/lib下可以找到这个动态链接库。

**Comment by sdcb** [comment]
我来解释一下，这个bug是因为官方提供的C编译库中，忘记将libphi.so打包了，但C++预先编译库提供了，因此临时的解决办法是可以下载C++版本，然后将C++包中的libphi.so拷到自己的项目中即可。

**Comment by magicleo** [comment]
> 我来解释一下，这个bug是因为官方提供的C编译库中，忘记将libphi.so打包了，但C++预先编译库提供了，因此临时的解决办法是可以下载C++版本，然后将C++包中的libphi.so拷到自己的项目中即可。

👍，被困扰了好久，果然copy过去就能解决
