### ISSUE TITLE
编译resnet50时出错，缺少dnnl.dll,但是下载的预测库里本身就没有

### ISSUE THREAD

**Issue by psychedelicosisyphus** [PaddlePaddle/Paddle-Inference-Demo#506]
![1](https://github.com/PaddlePaddle/Paddle-Inference-Demo/assets/149128242/64f1273e-345a-4851-a13d-a193a8fc6423)
![2](https://github.com/PaddlePaddle/Paddle-Inference-Demo/assets/149128242/8bbbe0ae-1c3e-404c-9206-0fb0fc8592e6)

**Comment by xiaoxiaohehe001** [comment]
@psychedelicosisyphus 目前问题已修复，对应pr，https://github.com/PaddlePaddle/Paddle-Inference-Demo/pull/509，感谢使用
