### ISSUE TITLE
在ubuntu20环境下g++9.4编译了2.3和2.6，用的resnet50 demo，编译通过，但是缺少so文件，把这些文件加入到环境变量也不行，请问是什么原因？

### ISSUE THREAD

**Issue by funny000** [PaddlePaddle/Paddle-Inference-Demo#512]

**Comment by vivienfanghuagood** [comment]
请问还有相关的问题吗？

**Comment by funny000** [comment]
暂时没有了，




2152550864
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle-Inference-Demo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月12日(星期五) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle-Inference-Demo] 在ubuntu20环境下g++9.4编译了2.3和2.6，用的resnet50 demo，编译通过，但是缺少so文件，把这些文件加入到环境变量也不行，请问是什么原因？ (Issue #512)





 
请问还有相关的问题吗？
